input.onButtonPressed(Button.A, function () {
    strip.setPixelColor(0, neopixel.rgb(255, 0, 0))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(0, 255, 0))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(0, 0, 255))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(0, 0, 0))
    strip.show()
})
input.onButtonPressed(Button.B, function () {
    strip.setPixelColor(0, neopixel.rgb(255, 255, 0))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(255, 0, 255))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(0, 255, 255))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(0, 0, 0))
    strip.show()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    strip.setPixelColor(0, neopixel.rgb(255, 255, 255))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(0, neopixel.rgb(0, 0, 0))
    strip.show()
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P0, 6, NeoPixelMode.RGB)
strip.setBrightness(2)
